### ISSUE TITLE
Left Option (Alt) Key does not trigger the character compose mode

### ISSUE THREAD

**Issue by maddrag0n** [thure/abc-extended#1]
This works as expected for the right Option/Alt key.

Is there any way to get this also working on left Option (Alt) Key as on macOS?

- Windows 11 Home 23H2 (22631.4037)
- Windows Feature Experience Pack 1000.22700.1027.0
- MS PowerToys v0.83.0

**Comment by thure** [comment]
This makes some sense, since Windows binds Alt to commands and makes AltGr on the right available for keyboard layouts like this one.

According to [this forum post](https://forum.colemak.com/topic/2156-change-left-shift-and-left-alt-with-msklc/), it may not be possible to map regular (left) Alt using MSKLC as it's not available in the Shiftstate.

If you do find a solution, though, I'd be glad for a pull request!

**Comment by maddrag0n** [comment]
To summarize:

- The current shift state modifier is actually AltGr, which for legacy reason is mapped to Alt (right) on newer keyboards
  - meaning you can actually use Ctrl + Alt (left) as a workaround for now (tho UX wise that defeats the purpose as we want to come as close to the macOS experience as possible)
- MSKLC does not support Alt (left) as a shift state modifier. This might be because of keyboard layouts not supporting Alt as a shift state modifier on Windows
  - guessing from the klc file, shift state is actually provided as a bitmask and therefore predetermined to specific combinations
- The only workaround as suggested by a user in the thread you linked would be to remap using registry, which potentially breaks other apps

Unfortunately, I could also not find any repository for MSKLC top open a feature request.

Closing, as this seems to be not solvable within the constraints of MSKLC
